### ISSUE TITLE
Hello from Toptout!

### ISSUE THREAD

**Issue by beatcracker** [herrbischoff/telemetry#1]
Hi there!

I'm running a very similar project that collects data about telemetry in applications in machine-readable format and makes it easy to create derivative works such as awesome-lists, configuration scripts, APIs, etc.

* https://github.com/beatcracker/toptout

Your work came to my attention recently (https://github.com/beatcracker/toptout/issues/61) and I'm going to mention your project in the [Related projects](https://github.com/beatcracker/toptout#related-projects) section of the README. I hope that you're fine with that 😄 .

Cheers!

**Comment by herrbischoff** [comment]
Sure.
